# Generated by Django 3.1.6 on 2021-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=600, null=True, upload_to='', width_field=600),
        ),
    ]
