# Generated by Django 3.1.6 on 2021-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210215_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.99, max_digits=1000),
            preserve_default=False,
        ),
    ]
