# Generated by Django 3.1.6 on 2021-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='m', height_field=600, upload_to='', width_field=600),
            preserve_default=False,
        ),
    ]
